### ISSUE TITLE
[request] return pacman for feedback during scan

### ISSUE THREAD

**Issue by ianamk** [ariccio/altWinDirStat#16]
one of the little bits of the old windirstat was the tiny packman eating at folders shown during file space analyses while I do agree they served no real purpose they wore fun and usefull to know that the application is busy not frozen
https://imgur.com/a/6QIyN
is it possible to have them back
currently altWinDirStat has no feedback that it's working (it looks frozen) during analyses if I didn't know it was working I'd thing altWinDirStat froze and needs to be killed

**Comment by assarbad** [comment]
Just FYI, this "feature" is also slated for removal from the original WinDirStat. At the very least it'll be turned off by default in the future, but more likely it'll be removed altogether.

**Comment by ariccio** [comment]
No. That feature was a PITA. Sorry, but nah. Not gonna do it. Nuh-uh.
